version: "2.3"
networks:
  default:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - container-volume:./src/database/dump
